add_executable(turtle335_core_tests tests/test_adt_core.cpp)
target_link_libraries(turtle335_core_tests PRIVATE turtle335_core)

add_executable(turtle335_mcnk_tests tests/test_mcnk_writer.cpp)
target_link_libraries(turtle335_mcnk_tests PRIVATE turtle335_core)

add_executable(turtle335_full_adt_tests tests/test_full_adt_writer.cpp)
target_link_libraries(turtle335_full_adt_tests PRIVATE turtle335_core)

add_executable(turtle335_terrain_tests tests/test_terrain_writer.cpp)
target_link_libraries(turtle335_terrain_tests PRIVATE turtle335_core)

add_executable(turtle335_fixture_a_tests tests/test_fixture_a.cpp)
target_link_libraries(turtle335_fixture_a_tests PRIVATE turtle335_core)

add_executable(turtle335_wdt_tests tests/test_wdt_writer.cpp)
target_link_libraries(turtle335_wdt_tests PRIVATE turtle335_core)

add_executable(turtle335_normalized_adt_tests tests/test_normalized_adt.cpp)
target_link_libraries(turtle335_normalized_adt_tests PRIVATE turtle335_core)

add_executable(turtle335_wotlk_adt_reader_tests tests/test_wotlk_adt_reader.cpp)
target_link_libraries(turtle335_wotlk_adt_reader_tests PRIVATE turtle335_core)

add_executable(turtle335_wotlk_adt_probe_tests tests/test_wotlk_adt_probe.cpp)
target_link_libraries(turtle335_wotlk_adt_probe_tests PRIVATE turtle335_core)

add_executable(turtle335_wotlk_map_probe_tests tests/test_wotlk_map_probe.cpp)
target_link_libraries(turtle335_wotlk_map_probe_tests PRIVATE turtle335_core)

add_executable(turtle335_wotlk_terrain_normalizer_tests tests/test_wotlk_terrain_normalizer.cpp)
target_link_libraries(turtle335_wotlk_terrain_normalizer_tests PRIVATE turtle335_core)

add_executable(turtle335_wotlk_mcsh_normalizer_tests tests/test_wotlk_mcsh_normalizer.cpp)
target_link_libraries(turtle335_wotlk_mcsh_normalizer_tests PRIVATE turtle335_core)

add_executable(turtle335_wotlk_adt_normalizer_tests tests/test_wotlk_adt_normalizer.cpp)
target_link_libraries(turtle335_wotlk_adt_normalizer_tests PRIVATE turtle335_core)

add_executable(turtle335_liquid_type_dbc_tests tests/test_liquid_type_dbc.cpp)
target_link_libraries(turtle335_liquid_type_dbc_tests PRIVATE turtle335_core)

add_executable(turtle335_wotlk_wdt_reader_tests tests/test_wotlk_wdt_reader.cpp)
target_link_libraries(turtle335_wotlk_wdt_reader_tests PRIVATE turtle335_core)

add_executable(turtle335_raw_wotlk_pipeline_tests tests/test_raw_wotlk_pipeline.cpp)
target_link_libraries(turtle335_raw_wotlk_pipeline_tests PRIVATE turtle335_core)

add_executable(turtle335_m2_core_tests tests/test_m2_core.cpp)
target_link_libraries(turtle335_m2_core_tests PRIVATE turtle335_core)

add_executable(turtle335_external_anim_tests tests/test_external_anim.cpp)
target_link_libraries(turtle335_external_anim_tests PRIVATE turtle335_core)

add_executable(turtle335_quaternion_codec_tests tests/test_quaternion_codec.cpp)
target_link_libraries(turtle335_quaternion_codec_tests PRIVATE turtle335_core)

add_executable(turtle335_bone_writer_tests tests/test_bone_writer.cpp)
target_link_libraries(turtle335_bone_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_auxiliary_track_writer_tests tests/test_auxiliary_track_writers.cpp)
target_link_libraries(turtle335_auxiliary_track_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_camera_writer_tests tests/test_camera_writer.cpp)
target_link_libraries(turtle335_camera_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_event_writer_tests tests/test_event_writer.cpp)
target_link_libraries(turtle335_event_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_light_writer_tests tests/test_light_writer.cpp)
target_link_libraries(turtle335_light_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_classic_m2_header_tests tests/test_classic_m2_header.cpp)
target_link_libraries(turtle335_classic_m2_header_tests PRIVATE turtle335_core)

add_executable(turtle335_ribbon_writer_tests tests/test_ribbon_writer.cpp)
target_link_libraries(turtle335_ribbon_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_particle_writer_tests tests/test_particle_writer.cpp)
target_link_libraries(turtle335_particle_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_skin_view_writer_tests tests/test_skin_view_writer.cpp)
target_link_libraries(turtle335_skin_view_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_classic_m2_validator_tests tests/test_classic_m2_validator.cpp)
target_link_libraries(turtle335_classic_m2_validator_tests PRIVATE turtle335_core)

add_executable(turtle335_classic_m2_writer_tests tests/test_classic_m2_writer.cpp)
target_link_libraries(turtle335_classic_m2_writer_tests PRIVATE turtle335_core)

add_executable(turtle335_effect_validator_tests tests/m2/effect/EffectValidatorTests.cpp)
target_link_libraries(turtle335_effect_validator_tests PRIVATE turtle335_core)

add_executable(turtle335_particle_validator_tests
    tests/m2/particle/ParticleValidatorTests.cpp
)

add_executable(turtle335_particle_probe_tests
    tests/m2/particle/ParticleProbeTests.cpp
)


target_link_libraries(
    turtle335_particle_probe_tests
    turtle335_core
)


add_test(
    NAME turtle335_particle_probe_tests
    COMMAND turtle335_particle_probe_tests
)

add_executable(turtle335_particle_reader_tests
    tests/m2/particle/ParticleReaderTests.cpp
)


target_link_libraries(
    turtle335_particle_reader_tests
    turtle335_core
)


add_test(
    NAME turtle335_particle_reader_tests
    COMMAND turtle335_particle_reader_tests
)

target_link_libraries(
    turtle335_particle_validator_tests
    PRIVATE turtle335_core
)

enable_testing()
add_test(NAME turtle335_core_tests COMMAND turtle335_core_tests)
add_test(NAME turtle335_mcnk_tests COMMAND turtle335_mcnk_tests)
add_test(NAME turtle335_full_adt_tests COMMAND turtle335_full_adt_tests)
add_test(NAME turtle335_terrain_tests COMMAND turtle335_terrain_tests)
add_test(NAME turtle335_fixture_a_tests COMMAND turtle335_fixture_a_tests)
add_test(NAME turtle335_wdt_tests COMMAND turtle335_wdt_tests)
add_test(NAME turtle335_normalized_adt_tests COMMAND turtle335_normalized_adt_tests)
add_test(NAME turtle335_wotlk_adt_reader_tests COMMAND turtle335_wotlk_adt_reader_tests)
add_test(NAME turtle335_wotlk_adt_probe_tests COMMAND turtle335_wotlk_adt_probe_tests)
add_test(NAME turtle335_wotlk_map_probe_tests COMMAND turtle335_wotlk_map_probe_tests)
add_test(NAME turtle335_wotlk_terrain_normalizer_tests COMMAND turtle335_wotlk_terrain_normalizer_tests)
add_test(NAME turtle335_wotlk_mcsh_normalizer_tests COMMAND turtle335_wotlk_mcsh_normalizer_tests)
add_test(NAME turtle335_wotlk_adt_normalizer_tests COMMAND turtle335_wotlk_adt_normalizer_tests)
add_test(NAME turtle335_liquid_type_dbc_tests COMMAND turtle335_liquid_type_dbc_tests)
add_test(NAME turtle335_wotlk_wdt_reader_tests COMMAND turtle335_wotlk_wdt_reader_tests)
add_test(NAME turtle335_raw_wotlk_pipeline_tests COMMAND turtle335_raw_wotlk_pipeline_tests)
add_test(NAME turtle335_m2_core_tests COMMAND turtle335_m2_core_tests)
add_test(NAME turtle335_external_anim_tests COMMAND turtle335_external_anim_tests)
add_test(NAME turtle335_quaternion_codec_tests COMMAND turtle335_quaternion_codec_tests)
add_test(NAME turtle335_bone_writer_tests COMMAND turtle335_bone_writer_tests)
add_test(NAME turtle335_auxiliary_track_writer_tests COMMAND turtle335_auxiliary_track_writer_tests)
add_test(NAME turtle335_camera_writer_tests COMMAND turtle335_camera_writer_tests)
add_test(NAME turtle335_event_writer_tests COMMAND turtle335_event_writer_tests)
add_test(NAME turtle335_light_writer_tests COMMAND turtle335_light_writer_tests)
add_test(NAME turtle335_classic_m2_header_tests COMMAND turtle335_classic_m2_header_tests)
add_test(NAME turtle335_ribbon_writer_tests COMMAND turtle335_ribbon_writer_tests)
add_test(NAME turtle335_effect_validator_tests COMMAND turtle335_effect_validator_tests)
add_test(NAME turtle335_particle_validator_tests COMMAND turtle335_particle_validator_tests)
add_test(NAME turtle335_particle_writer_tests COMMAND turtle335_particle_writer_tests)
add_test(NAME turtle335_skin_view_writer_tests COMMAND turtle335_skin_view_writer_tests)
add_test(NAME turtle335_classic_m2_validator_tests COMMAND turtle335_classic_m2_validator_tests)
add_test(NAME turtle335_classic_m2_writer_tests COMMAND turtle335_classic_m2_writer_tests)